// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REDACTED',
    appId: '1:835153358774:web:0601e0f43b27a56af05b17',
    messagingSenderId: '835153358774',
    projectId: 'habit-control-58eb0',
    authDomain: 'habit-control-58eb0.firebaseapp.com',
    storageBucket: 'habit-control-58eb0.firebasestorage.app',
    measurementId: 'G-YQ000KW8M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu2WCuXgh9o89yVAodD_ZFMy6PM3h1WfM',
    appId: '1:835153358774:android:ad3ae8f64eaf4e45f05b17',
    messagingSenderId: '835153358774',
    projectId: 'habit-control-58eb0',
    storageBucket: 'habit-control-58eb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REDACTED',
    appId: '1:835153358774:ios:5267530e53372a48f05b17',
    messagingSenderId: '835153358774',
    projectId: 'habit-control-58eb0',
    storageBucket: 'habit-control-58eb0.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REDACTED',
    appId: '1:835153358774:ios:5267530e53372a48f05b17',
    messagingSenderId: '835153358774',
    projectId: 'habit-control-58eb0',
    storageBucket: 'habit-control-58eb0.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REDACTED',
    appId: '1:835153358774:web:9605783ccf4feebff05b17',
    messagingSenderId: '835153358774',
    projectId: 'habit-control-58eb0',
    authDomain: 'habit-control-58eb0.firebaseapp.com',
    storageBucket: 'habit-control-58eb0.firebasestorage.app',
    measurementId: 'G-2D5QB3WJXT',
  );
}
