// File generated by FlutterFire CLI (edited: Android-only).
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// FirebaseOptions solo para Android.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => android;

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZpf0eL59zmgzX2-3QUpYnbqd3-EQ0yig',
    appId: '1:835153358774:android:ad3ae8f64eaf4e45f05b17',
    messagingSenderId: '835153358774',
    projectId: 'habit-control-58eb0',
    storageBucket: 'habit-control-58eb0.firebasestorage.app',
  );
}
